bot_settings:
  max_seen_items: 1000
  max_telegram_messages_per_item: 10   # None or omit to disable limit
  seen_file: seen_items.json
  telegram_max_retries: 5
  telegram_backoff_factor: 2.5

schedule:
  daily_summary_time: "12:30"

delays:
  keyword_batch_delay: 5
  full_cycle_delay: 10
  telegram_min_delay: 1.5

# Mapping: display name (key) -> search term (value)
keywords:
  ps3:
    term: プレイステーション3 (PS3) 本体
    price_min: 4000
    price_max: 10000
    title_must_contain:
      - 本体
  ps4:
    term: プレイステーション4 (PS4) 本体
    price_min: 7000
    price_max: 15000
    title_must_contain:
      - 本体